# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca7c9b5dc571946e2707a57f02ef16afe58977a01c54519d64cb0b71503689dff2a6570f37fd26553515aace04156ec4736094fb3a8d70f862265310fe9cfee1

test:
  secret_key_base: c33cb4c10cfb8b0ef6d17ec1246af3d2c49e3206ef9644913b6ade6b6a6d8413a24842d4ea3d5e5d785b9f989f2297c2226fc53a234950717cabc7f804ff13be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
